### ISSUE TITLE
Visualization of the attention mechanism

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#10]
Start with a system as specified in #9 
<img width="222" alt="Screenshot 2023-11-22 alle 12 17 27" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/0509e579-33a1-430b-868f-0a54025e9695">

Make and animation that draws all the lines connecting each couple of elements.
<img width="233" alt="Screenshot 2023-11-22 alle 12 27 49" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/0663661b-0b08-4f55-a7a9-ed6abd443b6a">

each line connecting the node $i$ with the node $j$ will have a value associated to it equal to `line[i][j]`.
The color of each line will be determined by mapping its value with a color map [like the ones from matplotlib](https://matplotlib.org/stable/gallery/color/colormap_reference.html)
<img width="575" alt="Screenshot 2023-11-22 alle 12 31 47" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/943caba5-b57f-44c7-9de9-bbaf8429f22f">

# Warning
I'm bringing up matplotlib because i'm not sure if you can use a colormap in manim. I did a quick search but the stuff i found is a bit ambigous...

If you can't use a colormap in manim it means that you probably will have to use matplotlib in all of the other animations related to this one (#7,  #8 and #9). [Btw, i found a cool tutorial to get started with matplotlib ](https://youtu.be/yaa13eehgzo?si=IRrZioufGDPJzpXg&t=450)

If you can use a colormap in Manim, great! it means you can do as you please

**Comment by n-shevko** [comment]
Done. project/utils/attention.py  connect_tokens

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/ead1c3a5-482b-4fea-bc51-cc3504840421

**Comment by Francesco215** [comment]
https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/9ede3c2e-d127-40dd-a030-0819443f871d
