### ISSUE TITLE
Highlight attention links

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#11]
Start with a system as specified in #10
<img width="333" alt="Screenshot 2023-11-22 alle 12 27 49" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/0663661b-0b08-4f55-a7a9-ed6abd443b6a">

Write a function that implements an animation that highlight a set of links.
By highighting i mean a combination of this three features:

- increasing the width and opacity of the links highlited
- deacreasing the width and opacity of the links not highlighted
- wiggling the links highlighted (facoltative, it depends if it actually looks good or is necessary)

<img width="319" alt="Screenshot 2023-11-22 alle 15 11 35" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/ef611b85-5d49-4993-a709-7c588430b1ac">

the highlited link can be also just one of them, probably one way of doing it would be like defining a function `highlight_links(links)`, and the `links` variable is a list of tuples like `[(1,2),(6,8),(6,1)]`. In this particular case the connection between the indices `1` and `2`, `6` and `8` and `6` and `1` will be highlited, all the others will be dimmed down

**Comment by n-shevko** [comment]
Done. project/utils/attention.py  highlight_links
Also wiggling can be done by Wiggle class


https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/6655a62a-8e3a-4388-9ec7-015dac9d2b5a

**Comment by Francesco215** [comment]
Great! Good job!
