### ISSUE TITLE
arrows for the chain

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#14]
we need a function `draw_arrows_for_chain()` that returns an animation that draws arrows connecting different circles

![IMG_035303ED9277-1](https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/e6d251c7-e700-458a-a6c8-f913644f4664)
----
## some details

the function `draw_arrows_for_chain(links)` has as argument `links` that is an array that specifies where the arrow start from and where they go (similar to how you did the functions that connect the circles for the animation below) 

https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/7a3202f7-09b2-476c-8929-212fabda7a78

make sure it's compatible with the code for issue #13

**Comment by n-shevko** [comment]
Done. function draw_arrows_for_chain


https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/9e8d1387-bff0-4321-89bc-3baa1e648c00

**Comment by Francesco215** [comment]
looks good 👍
