### ISSUE TITLE
square around the circles

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#15]
Write an function `make_square(start:int,end:int,color)`

that draws a square of color `color` encapsulating all the circles from the index `start` to the index `end`

the circles are in the "straight formation"
<img width="825" alt="Screenshot 2023-11-27 alle 18 36 46" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/49adfdc8-9212-4c06-bb34-5b66115d4d33">

**Comment by n-shevko** [comment]
Done. function make_square 

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/8700baa8-a149-49d1-a64f-258cd48a8166

Is it doing what you need ?

**Comment by Francesco215** [comment]
nono, something like [`SurroundingRectangle`](https://docs.manim.community/en/stable/reference/manim.mobject.geometry.shape_matchers.SurroundingRectangle.html)

Also, i forgot to mention in the issue that we also need a funciton that translates the square 

something like `translate_square(i:int)` where `i` represents by how many steps the square has to do

**Comment by n-shevko** [comment]
Done. functions make_square translate_square

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/d8f12561-6855-4635-ab1c-5ce7f584eca7

Everything is ok ?

**Comment by Francesco215** [comment]
That's great!
