### ISSUE TITLE
Plotting a network

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#16]
Ok i said there could be the need for an extra animation, and there is

We need a function that plots a network with manim called something like `plot_network(nodes, edges)` and it will show something like this

![immagine](https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/5685a98b-fe15-4334-9270-98ab2b0b7012)

The main difference with the image is that the `nodes` can have two possible values (0 or 1), so they can have two colors `WHITE` or `BLACK`, and we also need a function that animates the color changes. Maybe we can just reuse the [`update_fill`](https://github.com/Francesco215/requirements_for_self-organization_video/blob/dc973d13eebc63626fb4af3d19e7eacf4f4459d5/project/utils/utils.py#L35C1-L35C72) function already present in the code

The edges will be an $N\times N$ numpy matrix with values either equal to 0 or 1. If you want to generate one that will make a pretty cool graph use the [`small_world`](https://github.com/Francesco215/requirements_for_self-organization_video/blob/87d7e0f7bcf728e2359d190dd2148aed869bcf9c/project/utils/utils.py#L46) function

The edges can all have the same color `hamiltonian_color`

### Some extra things

There are several ways to choose the positions of the nodes, the easiest one would be to choose them at random inside the frame.

However there are some ploblems with this method (like nodes overlapping and the entire thing looking very garbled), so there are more advanced tecniques of plotting graphs, so look into those, there should be some premade python function out there

### Some links to look into

Manim has a [`Graph`](https://docs.manim.community/en/stable/reference/manim.mobject.graph.Graph.html) mobject class, might be wise to look into it

**Comment by n-shevko** [comment]
Done. project/utils/attention.py  functions   plot_network  update_fill_for_graph


https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/28cf2ea6-74c8-407a-a0a2-2a7e85c0ff59

**Comment by Francesco215** [comment]
Great!
