### ISSUE TITLE
Snake-ising model

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#17]
We need an animation that draws lots of circles in a snake pattern like the one of the website

<img width="684" alt="Screenshot 2023-12-13 alle 19 08 32" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/f5452c68-240d-4fd4-a725-4d43000d56e7">

As usual each node can have two possible values (0 or 1), so they can have two colors `WHITE` or `BLACK`, and we also need a function that animates the color changes. Maybe we can just reuse the [`update_fill`](https://github.com/Francesco215/requirements_for_self-organization_video/blob/dc973d13eebc63626fb4af3d19e7eacf4f4459d5/project/utils/utils.py#L35C1-L35C72) function already present in the code

Each circle will be connected by a segment with the color=`hamiltonian_color`

i'd say that is better to put the code in a separate python file inside the project folder

### Tip

In the [website code](https://github.com/Francesco215/Language_CA/blob/930588163cc88b3f2f47eccc301a9ab0cf86ef2a/website/scripts/1Dising.js#L83C1-L95C2) i wrote a function that returns the realtive position in a $i,j$ grid of all the elements in the serpentine, i think translating this in python this will make your job easier.

I don't know how deep i have to go into the explanation of this function, but printing the output a couple of times should be enough. if you need any clarifiaction you can always ask

```javascript
function Serpentine(i, nSH) {
        //nSH represents the variable numSpinsHorizontal
        if (i<nSH) return [i, 0]
        if (i==nSH) return [nSH-1, 1]
        if (i<=2*nSH) return [2*nSH-i, 2]
        if (i==2*nSH+1) return [0,3]
        
        
        let recursive=Serpentine(i%(2*(nSH+1)),nSH);
        recursive[1]+=4*Math.floor(i/(2*nSH+2));
        
        return recursive
}
```

**Comment by n-shevko** [comment]
Done. project/snake_ising.py functions create_snake  update_snake_colors

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/3fbfab71-c5de-452b-af61-7a8b13bfd9c7

**Comment by Francesco215** [comment]
Good job!
