### ISSUE TITLE
Add demarcation line between neighboring spins

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#2]
In the spin grid, when it looks like in the image below
<img width="405" alt="Screenshot 2023-11-06 alle 12 23 51" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/8ddbe843-db85-454a-a694-e42fa440f282">

i would like to have a function that returns an animation that draws the boundary between the white squares and the black squares

**Comment by n-shevko** [comment]
Done

https://github.com/Francesco215/requirements_for_self-organization_video/blob/897e6e5af3942971b7deda165101cf1c00d38eb7/project/spin_grid.py#L166
