### ISSUE TITLE
De-zoom ising 2D

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#3]
As of now the 2D grid is shaped in such a way that it fits inside the window size.

However, we need an animation that looks at the system from further away 

Something similar to [this video](https://www.youtube.com/shorts/ySkn6gQroCI)

Make sure it supports the feature in #2

**Comment by n-shevko** [comment]
use update_colors2 to switch colors if you want then zoom out the grid

https://github.com/Francesco215/requirements_for_self-organization_video/blob/556f88ee2f1c5778a30268b532fe0bfc50ecb737/project/spin_grid.py#L193

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/666bbc18-4df0-4fdf-9d31-8070edfa193e

**Comment by Francesco215** [comment]
In the video you sent, when it unzooms there is nothing around the grid ([unlike the animation on the video i linked before](https://www.youtube.com/shorts/ySkn6gQroCI)).

Do i just have to initialize the grid at the start in such a way that its larger than then frame?

**Comment by n-shevko** [comment]
> In the video you sent, when it unzooms there is nothing around the grid ([unlike the animation on the video i linked before](https://www.youtube.com/shorts/ySkn6gQroCI)).
> 
> Do i just have to initialize the grid at the start in such a way that its larger than then frame?

You should set radius= some_number   here:  make_grid(starting_state, self, radius=0.5)

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/13ea0037-5e58-4dd1-831f-8049873f72bb

**Comment by Francesco215** [comment]
okok great thanks!
