### ISSUE TITLE
Problem with laser beams

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#4]
Here the lines should "undraw" themeselves from the source instead of the target

https://github.com/Francesco215/requirements_for_self-organization_video/blob/94d68821fd2a1fb026599e27cdfecb1f613b78d3/project/fc_ising.py#L56C1-L58

https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/d08809c1-55d7-493b-8165-ec1d592d8c7f

the [`Unwrite`](https://docs.manim.community/en/stable/reference/manim.animation.creation.Unwrite.html) function doesn't work and the [`Uncreate`](https://docs.manim.community/en/stable/reference/manim.animation.creation.Uncreate.html) function cannot be reversed.

**Comment by n-shevko** [comment]
Done

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/261a174c-ce5d-4d76-bc13-b12223c123ab

**Comment by Francesco215** [comment]
This is good, however maybe its better to make it more like some kind of laser beams shooting out.

In any case for now its better to cosider the other issues as they are more important, I'll lower the priority on this one since its more or less good enough
