### ISSUE TITLE
2D boundaries drawing animation

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#5]
In the current representation, the boundary delineating opposing spins in the 2D Ising model is constructed by animating the drawing of individual segments in an independent manner.

Instead of isolating each segment, consider a method where the boundary is drawn by tracing around the collective path formed by opposing spins.

If two domains meet at just one corner split the two domains like in the image below
<img width="318" alt="Screenshot 2023-11-14 alle 11 56 50" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/ac8405e9-fde0-4b83-a345-a8aa1389987f">

a useful example you might want to look at is [the one where a point draws a trace](https://docs.manim.community/en/stable/examples.html#pointwithtrace)

**Comment by Francesco215** [comment]
Also, this is probably going to get solved with the fixing of this issue, but make sure that at the corners the demarcations line looks good even if the demarcation line is thick


https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/e417a007-ff24-4334-a806-1ee05bfa1ac6

**Comment by n-shevko** [comment]
Done. Function tracking_boundaries
https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/8673bb64-8615-48eb-95d8-4b28140a9ed7

**Comment by Francesco215** [comment]
Great! 

Just one last thing: Can you add the functionality for the moving dot to disappear when it's done moving?

**Comment by n-shevko** [comment]
Done

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/3eb706fa-d310-4b6d-a01f-fad188421c09

**Comment by Francesco215** [comment]
great!
