### ISSUE TITLE
Problems after zooming out

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#6]
here in the video i zoom out and then change color of one square, and then draw the boundaries.

https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/dfe49e4d-0868-49dc-95db-5841fd6f3b12

as you can see the `grid['squares']` refer to the squares before doing the zooming out via the function `zoom_out` 

the code is in the [`spin_grid.py`](https://github.com/Francesco215/requirements_for_self-organization_video/blob/97ea6267280063d88b0d80a8dbf8c494b20febda/project/spin_grid.py#L42C9-L48C41) file and goes at follows:

 ```python
#zooming out
self.play(*zoom_out(grid,scale=.7), run_time=5)
#here the color is changed in the square as if it was never zoomed out
animation=grid['squares'][73].animate.set_color(RED)
self.play(animation)   
#here the boundaries are drawn as if the grid never zoomed out
self.play(*add_boundaries(grid))

```

**Comment by n-shevko** [comment]
Fixed. Don't know why but when something is animated the new object (in state "after animation is applied") located in animation.mobject  property

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/ca541fcc-b070-4c84-8103-8b5e1f8629fe

**Comment by Francesco215** [comment]
that was fast!

Thanks!
