### ISSUE TITLE
Tokenization

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#7]
# General description

write a function `tokenization(text)` that colors the text
<img width="689" alt="Screenshot 2023-11-22 alle 11 08 26" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/a24a6e81-5a90-4ff4-8903-c59ae53cea78">
The way it colors the text is explained [in this link](https://platform.openai.com/tokenizer)

### input
For our visualization purpuses the function tokenization takes a list of strings `text` where each element in the text is a token.

For example in the image above the input `text` will be `['Many',' words',' map',' to',' one',' token',...]`
### coloring
there will also be a list of colors that will be used to color the text. The `i`-th token will be colored with the color `colors[i%len(colors)]`

### output
It will return 2 animations:
- one that draws the text with no coloring
- one that colors the text 

If you prefer you can make two function (one for each animation)

**Comment by n-shevko** [comment]
Done.
project/spin_grid.py  tokenization function

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/9d57502c-d463-4768-b1a5-8d38e410892e

**Comment by Francesco215** [comment]
great! I tweaked the code a bit, remember to pull
