### ISSUE TITLE
Tokenized text into a sequence of circles

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#8]
You start with a text generated from the `tokenize` function defined in #7 
<img width="689" alt="Screenshot 2023-11-22 alle 11 08 26" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/a24a6e81-5a90-4ff4-8903-c59ae53cea78">

then each token is turned into a variable name $s_1,s_2,\dots,s_n$ and put inside a circle with the same color of the token

(something similar to this, but with circles instead of squares and colored)
<img width="607" alt="Screenshot 2023-11-22 alle 11 19 29" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/4cbc2e1d-b5fc-4259-88a1-7c72b1f6ade2">

**Comment by n-shevko** [comment]
Done. 
project/utils/attention.py   tokens_to_variables

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/28bb960a-218a-4d10-b991-98a067a24ca1

**Comment by Francesco215** [comment]
great!

Just one minor thing... Can you make sure that the chain is centered?

I don't mean of adding an extra step to the animation that centers tha chain, rather making sure that the chain is generated at the center

**Comment by n-shevko** [comment]
Done

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/f2f2b1c8-8074-485e-a394-daa246b0c89d

**Comment by Francesco215** [comment]
Soo good!
