### ISSUE TITLE
Chain rolling

### ISSUE THREAD

**Issue by Francesco215** [Francesco215/requirements_for_self-organization_video#9]
Start with the sequence described in #8 
<img width="607" alt="Screenshot 2023-11-22 alle 11 19 29" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/4cbc2e1d-b5fc-4259-88a1-7c72b1f6ade2">

We need a function `roll_chain` that rolls all the elements of the sequence $s_0, ..., s_N$  into a circle like so
<img width="622" alt="Screenshot 2023-11-22 alle 12 17 27" src="https://github.com/Francesco215/requirements_for_self-organization_video/assets/47751420/0509e579-33a1-430b-868f-0a54025e9695">

**Comment by n-shevko** [comment]
Done.
roll_chain

https://github.com/Francesco215/requirements_for_self-organization_video/assets/11594789/0349d130-a661-471c-885f-919912a7ab16
